name: main test
on: push
jobs: 
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install
        run: 
          npm install
      - name: Run jest
        run: 
          make test
      - name: Test and publish code coverage
        env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_COVERAGE }}